// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: pb/task_forward/task_forward.proto

package task_forward

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskForwardClient is the client API for TaskForward service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskForwardClient interface {
	Foo(ctx context.Context, opts ...grpc.CallOption) (TaskForward_FooClient, error)
}

type taskForwardClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskForwardClient(cc grpc.ClientConnInterface) TaskForwardClient {
	return &taskForwardClient{cc}
}

func (c *taskForwardClient) Foo(ctx context.Context, opts ...grpc.CallOption) (TaskForward_FooClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaskForward_ServiceDesc.Streams[0], "/task_forward.TaskForward/Foo", opts...)
	if err != nil {
		return nil, err
	}
	x := &taskForwardFooClient{stream}
	return x, nil
}

type TaskForward_FooClient interface {
	Send(*FooResponse) error
	Recv() (*FooRequest, error)
	grpc.ClientStream
}

type taskForwardFooClient struct {
	grpc.ClientStream
}

func (x *taskForwardFooClient) Send(m *FooResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *taskForwardFooClient) Recv() (*FooRequest, error) {
	m := new(FooRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskForwardServer is the server API for TaskForward service.
// All implementations must embed UnimplementedTaskForwardServer
// for forward compatibility
type TaskForwardServer interface {
	Foo(TaskForward_FooServer) error
	mustEmbedUnimplementedTaskForwardServer()
}

// UnimplementedTaskForwardServer must be embedded to have forward compatible implementations.
type UnimplementedTaskForwardServer struct {
}

func (UnimplementedTaskForwardServer) Foo(TaskForward_FooServer) error {
	return status.Errorf(codes.Unimplemented, "method Foo not implemented")
}
func (UnimplementedTaskForwardServer) mustEmbedUnimplementedTaskForwardServer() {}

// UnsafeTaskForwardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskForwardServer will
// result in compilation errors.
type UnsafeTaskForwardServer interface {
	mustEmbedUnimplementedTaskForwardServer()
}

func RegisterTaskForwardServer(s grpc.ServiceRegistrar, srv TaskForwardServer) {
	s.RegisterService(&TaskForward_ServiceDesc, srv)
}

func _TaskForward_Foo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskForwardServer).Foo(&taskForwardFooServer{stream})
}

type TaskForward_FooServer interface {
	Send(*FooRequest) error
	Recv() (*FooResponse, error)
	grpc.ServerStream
}

type taskForwardFooServer struct {
	grpc.ServerStream
}

func (x *taskForwardFooServer) Send(m *FooRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *taskForwardFooServer) Recv() (*FooResponse, error) {
	m := new(FooResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskForward_ServiceDesc is the grpc.ServiceDesc for TaskForward service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskForward_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task_forward.TaskForward",
	HandlerType: (*TaskForwardServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Foo",
			Handler:       _TaskForward_Foo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/task_forward/task_forward.proto",
}
