version: "3"
x-common-variables: &common-variables
    PUSH_GATEWAY_URL: http://pushgateway.prometheus-docker.orb.local:9091
    REQUEST_PER_SECOND: 10000
    REQUEST_TIME_DURATION: 1800
    TASK_PER_WORKER: 100
    WORKER_COUNT: 100
    WORKER_IDLE_TIME: 5
    LISTEN_NETWORK: tcp
    LISTEN_ADDRESS: server:50015
    WORKER_TIMEOUT: 5
    SERVER_TIMEOUT: 10
x-worker-template: &worker-template
    image: grpc-bidirectional-streaming-worker:latest
    networks:
        general:
    deploy:
        resources:
            limits:
                cpus: "1"
                memory: 500M
services:
    worker_0001:
        <<: *worker-template
        container_name: worker_0001
        environment:
            <<: *common-variables
            WORKER_ID: worker_0001
    worker_0002:
        <<: *worker-template
        container_name: worker_0002
        environment:
            <<: *common-variables
            WORKER_ID: worker_0002
    worker_0003:
        <<: *worker-template
        container_name: worker_0003
        environment:
            <<: *common-variables
            WORKER_ID: worker_0003
    worker_0004:
        <<: *worker-template
        container_name: worker_0004
        environment:
            <<: *common-variables
            WORKER_ID: worker_0004
    worker_0005:
        <<: *worker-template
        container_name: worker_0005
        environment:
            <<: *common-variables
            WORKER_ID: worker_0005
    worker_0006:
        <<: *worker-template
        container_name: worker_0006
        environment:
            <<: *common-variables
            WORKER_ID: worker_0006
    worker_0007:
        <<: *worker-template
        container_name: worker_0007
        environment:
            <<: *common-variables
            WORKER_ID: worker_0007
    worker_0008:
        <<: *worker-template
        container_name: worker_0008
        environment:
            <<: *common-variables
            WORKER_ID: worker_0008
    worker_0009:
        <<: *worker-template
        container_name: worker_0009
        environment:
            <<: *common-variables
            WORKER_ID: worker_0009
    worker_0010:
        <<: *worker-template
        container_name: worker_0010
        environment:
            <<: *common-variables
            WORKER_ID: worker_0010
    worker_0011:
        <<: *worker-template
        container_name: worker_0011
        environment:
            <<: *common-variables
            WORKER_ID: worker_0011
    worker_0012:
        <<: *worker-template
        container_name: worker_0012
        environment:
            <<: *common-variables
            WORKER_ID: worker_0012
    worker_0013:
        <<: *worker-template
        container_name: worker_0013
        environment:
            <<: *common-variables
            WORKER_ID: worker_0013
    worker_0014:
        <<: *worker-template
        container_name: worker_0014
        environment:
            <<: *common-variables
            WORKER_ID: worker_0014
    worker_0015:
        <<: *worker-template
        container_name: worker_0015
        environment:
            <<: *common-variables
            WORKER_ID: worker_0015
    worker_0016:
        <<: *worker-template
        container_name: worker_0016
        environment:
            <<: *common-variables
            WORKER_ID: worker_0016
    worker_0017:
        <<: *worker-template
        container_name: worker_0017
        environment:
            <<: *common-variables
            WORKER_ID: worker_0017
    worker_0018:
        <<: *worker-template
        container_name: worker_0018
        environment:
            <<: *common-variables
            WORKER_ID: worker_0018
    worker_0019:
        <<: *worker-template
        container_name: worker_0019
        environment:
            <<: *common-variables
            WORKER_ID: worker_0019
    worker_0020:
        <<: *worker-template
        container_name: worker_0020
        environment:
            <<: *common-variables
            WORKER_ID: worker_0020
    worker_0021:
        <<: *worker-template
        container_name: worker_0021
        environment:
            <<: *common-variables
            WORKER_ID: worker_0021
    worker_0022:
        <<: *worker-template
        container_name: worker_0022
        environment:
            <<: *common-variables
            WORKER_ID: worker_0022
    worker_0023:
        <<: *worker-template
        container_name: worker_0023
        environment:
            <<: *common-variables
            WORKER_ID: worker_0023
    worker_0024:
        <<: *worker-template
        container_name: worker_0024
        environment:
            <<: *common-variables
            WORKER_ID: worker_0024
    worker_0025:
        <<: *worker-template
        container_name: worker_0025
        environment:
            <<: *common-variables
            WORKER_ID: worker_0025
    worker_0026:
        <<: *worker-template
        container_name: worker_0026
        environment:
            <<: *common-variables
            WORKER_ID: worker_0026
    worker_0027:
        <<: *worker-template
        container_name: worker_0027
        environment:
            <<: *common-variables
            WORKER_ID: worker_0027
    worker_0028:
        <<: *worker-template
        container_name: worker_0028
        environment:
            <<: *common-variables
            WORKER_ID: worker_0028
    worker_0029:
        <<: *worker-template
        container_name: worker_0029
        environment:
            <<: *common-variables
            WORKER_ID: worker_0029
    worker_0030:
        <<: *worker-template
        container_name: worker_0030
        environment:
            <<: *common-variables
            WORKER_ID: worker_0030
    worker_0031:
        <<: *worker-template
        container_name: worker_0031
        environment:
            <<: *common-variables
            WORKER_ID: worker_0031
    worker_0032:
        <<: *worker-template
        container_name: worker_0032
        environment:
            <<: *common-variables
            WORKER_ID: worker_0032
    worker_0033:
        <<: *worker-template
        container_name: worker_0033
        environment:
            <<: *common-variables
            WORKER_ID: worker_0033
    worker_0034:
        <<: *worker-template
        container_name: worker_0034
        environment:
            <<: *common-variables
            WORKER_ID: worker_0034
    worker_0035:
        <<: *worker-template
        container_name: worker_0035
        environment:
            <<: *common-variables
            WORKER_ID: worker_0035
    worker_0036:
        <<: *worker-template
        container_name: worker_0036
        environment:
            <<: *common-variables
            WORKER_ID: worker_0036
    worker_0037:
        <<: *worker-template
        container_name: worker_0037
        environment:
            <<: *common-variables
            WORKER_ID: worker_0037
    worker_0038:
        <<: *worker-template
        container_name: worker_0038
        environment:
            <<: *common-variables
            WORKER_ID: worker_0038
    worker_0039:
        <<: *worker-template
        container_name: worker_0039
        environment:
            <<: *common-variables
            WORKER_ID: worker_0039
    worker_0040:
        <<: *worker-template
        container_name: worker_0040
        environment:
            <<: *common-variables
            WORKER_ID: worker_0040
    worker_0041:
        <<: *worker-template
        container_name: worker_0041
        environment:
            <<: *common-variables
            WORKER_ID: worker_0041
    worker_0042:
        <<: *worker-template
        container_name: worker_0042
        environment:
            <<: *common-variables
            WORKER_ID: worker_0042
    worker_0043:
        <<: *worker-template
        container_name: worker_0043
        environment:
            <<: *common-variables
            WORKER_ID: worker_0043
    worker_0044:
        <<: *worker-template
        container_name: worker_0044
        environment:
            <<: *common-variables
            WORKER_ID: worker_0044
    worker_0045:
        <<: *worker-template
        container_name: worker_0045
        environment:
            <<: *common-variables
            WORKER_ID: worker_0045
    worker_0046:
        <<: *worker-template
        container_name: worker_0046
        environment:
            <<: *common-variables
            WORKER_ID: worker_0046
    worker_0047:
        <<: *worker-template
        container_name: worker_0047
        environment:
            <<: *common-variables
            WORKER_ID: worker_0047
    worker_0048:
        <<: *worker-template
        container_name: worker_0048
        environment:
            <<: *common-variables
            WORKER_ID: worker_0048
    worker_0049:
        <<: *worker-template
        container_name: worker_0049
        environment:
            <<: *common-variables
            WORKER_ID: worker_0049
    worker_0050:
        <<: *worker-template
        container_name: worker_0050
        environment:
            <<: *common-variables
            WORKER_ID: worker_0050
    worker_0051:
        <<: *worker-template
        container_name: worker_0051
        environment:
            <<: *common-variables
            WORKER_ID: worker_0051
    worker_0052:
        <<: *worker-template
        container_name: worker_0052
        environment:
            <<: *common-variables
            WORKER_ID: worker_0052
    worker_0053:
        <<: *worker-template
        container_name: worker_0053
        environment:
            <<: *common-variables
            WORKER_ID: worker_0053
    worker_0054:
        <<: *worker-template
        container_name: worker_0054
        environment:
            <<: *common-variables
            WORKER_ID: worker_0054
    worker_0055:
        <<: *worker-template
        container_name: worker_0055
        environment:
            <<: *common-variables
            WORKER_ID: worker_0055
    worker_0056:
        <<: *worker-template
        container_name: worker_0056
        environment:
            <<: *common-variables
            WORKER_ID: worker_0056
    worker_0057:
        <<: *worker-template
        container_name: worker_0057
        environment:
            <<: *common-variables
            WORKER_ID: worker_0057
    worker_0058:
        <<: *worker-template
        container_name: worker_0058
        environment:
            <<: *common-variables
            WORKER_ID: worker_0058
    worker_0059:
        <<: *worker-template
        container_name: worker_0059
        environment:
            <<: *common-variables
            WORKER_ID: worker_0059
    worker_0060:
        <<: *worker-template
        container_name: worker_0060
        environment:
            <<: *common-variables
            WORKER_ID: worker_0060
    worker_0061:
        <<: *worker-template
        container_name: worker_0061
        environment:
            <<: *common-variables
            WORKER_ID: worker_0061
    worker_0062:
        <<: *worker-template
        container_name: worker_0062
        environment:
            <<: *common-variables
            WORKER_ID: worker_0062
    worker_0063:
        <<: *worker-template
        container_name: worker_0063
        environment:
            <<: *common-variables
            WORKER_ID: worker_0063
    worker_0064:
        <<: *worker-template
        container_name: worker_0064
        environment:
            <<: *common-variables
            WORKER_ID: worker_0064
    worker_0065:
        <<: *worker-template
        container_name: worker_0065
        environment:
            <<: *common-variables
            WORKER_ID: worker_0065
    worker_0066:
        <<: *worker-template
        container_name: worker_0066
        environment:
            <<: *common-variables
            WORKER_ID: worker_0066
    worker_0067:
        <<: *worker-template
        container_name: worker_0067
        environment:
            <<: *common-variables
            WORKER_ID: worker_0067
    worker_0068:
        <<: *worker-template
        container_name: worker_0068
        environment:
            <<: *common-variables
            WORKER_ID: worker_0068
    worker_0069:
        <<: *worker-template
        container_name: worker_0069
        environment:
            <<: *common-variables
            WORKER_ID: worker_0069
    worker_0070:
        <<: *worker-template
        container_name: worker_0070
        environment:
            <<: *common-variables
            WORKER_ID: worker_0070
    worker_0071:
        <<: *worker-template
        container_name: worker_0071
        environment:
            <<: *common-variables
            WORKER_ID: worker_0071
    worker_0072:
        <<: *worker-template
        container_name: worker_0072
        environment:
            <<: *common-variables
            WORKER_ID: worker_0072
    worker_0073:
        <<: *worker-template
        container_name: worker_0073
        environment:
            <<: *common-variables
            WORKER_ID: worker_0073
    worker_0074:
        <<: *worker-template
        container_name: worker_0074
        environment:
            <<: *common-variables
            WORKER_ID: worker_0074
    worker_0075:
        <<: *worker-template
        container_name: worker_0075
        environment:
            <<: *common-variables
            WORKER_ID: worker_0075
    worker_0076:
        <<: *worker-template
        container_name: worker_0076
        environment:
            <<: *common-variables
            WORKER_ID: worker_0076
    worker_0077:
        <<: *worker-template
        container_name: worker_0077
        environment:
            <<: *common-variables
            WORKER_ID: worker_0077
    worker_0078:
        <<: *worker-template
        container_name: worker_0078
        environment:
            <<: *common-variables
            WORKER_ID: worker_0078
    worker_0079:
        <<: *worker-template
        container_name: worker_0079
        environment:
            <<: *common-variables
            WORKER_ID: worker_0079
    worker_0080:
        <<: *worker-template
        container_name: worker_0080
        environment:
            <<: *common-variables
            WORKER_ID: worker_0080
    worker_0081:
        <<: *worker-template
        container_name: worker_0081
        environment:
            <<: *common-variables
            WORKER_ID: worker_0081
    worker_0082:
        <<: *worker-template
        container_name: worker_0082
        environment:
            <<: *common-variables
            WORKER_ID: worker_0082
    worker_0083:
        <<: *worker-template
        container_name: worker_0083
        environment:
            <<: *common-variables
            WORKER_ID: worker_0083
    worker_0084:
        <<: *worker-template
        container_name: worker_0084
        environment:
            <<: *common-variables
            WORKER_ID: worker_0084
    worker_0085:
        <<: *worker-template
        container_name: worker_0085
        environment:
            <<: *common-variables
            WORKER_ID: worker_0085
    worker_0086:
        <<: *worker-template
        container_name: worker_0086
        environment:
            <<: *common-variables
            WORKER_ID: worker_0086
    worker_0087:
        <<: *worker-template
        container_name: worker_0087
        environment:
            <<: *common-variables
            WORKER_ID: worker_0087
    worker_0088:
        <<: *worker-template
        container_name: worker_0088
        environment:
            <<: *common-variables
            WORKER_ID: worker_0088
    worker_0089:
        <<: *worker-template
        container_name: worker_0089
        environment:
            <<: *common-variables
            WORKER_ID: worker_0089
    worker_0090:
        <<: *worker-template
        container_name: worker_0090
        environment:
            <<: *common-variables
            WORKER_ID: worker_0090
    worker_0091:
        <<: *worker-template
        container_name: worker_0091
        environment:
            <<: *common-variables
            WORKER_ID: worker_0091
    worker_0092:
        <<: *worker-template
        container_name: worker_0092
        environment:
            <<: *common-variables
            WORKER_ID: worker_0092
    worker_0093:
        <<: *worker-template
        container_name: worker_0093
        environment:
            <<: *common-variables
            WORKER_ID: worker_0093
    worker_0094:
        <<: *worker-template
        container_name: worker_0094
        environment:
            <<: *common-variables
            WORKER_ID: worker_0094
    worker_0095:
        <<: *worker-template
        container_name: worker_0095
        environment:
            <<: *common-variables
            WORKER_ID: worker_0095
    worker_0096:
        <<: *worker-template
        container_name: worker_0096
        environment:
            <<: *common-variables
            WORKER_ID: worker_0096
    worker_0097:
        <<: *worker-template
        container_name: worker_0097
        environment:
            <<: *common-variables
            WORKER_ID: worker_0097
    worker_0098:
        <<: *worker-template
        container_name: worker_0098
        environment:
            <<: *common-variables
            WORKER_ID: worker_0098
    worker_0099:
        <<: *worker-template
        container_name: worker_0099
        environment:
            <<: *common-variables
            WORKER_ID: worker_0099
    worker_0100:
        <<: *worker-template
        container_name: worker_0100
        environment:
            <<: *common-variables
            WORKER_ID: worker_0100
networks:
    general:
        external: true
