// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: pb/task/task.proto

package task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskClient interface {
	Foo(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooResponse, error)
	UpnpSearchExample(ctx context.Context, in *UpnpSearchRequest, opts ...grpc.CallOption) (Task_UpnpSearchExampleClient, error)
}

type taskClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskClient(cc grpc.ClientConnInterface) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) Foo(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooResponse, error) {
	out := new(FooResponse)
	err := c.cc.Invoke(ctx, "/task.Task/Foo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) UpnpSearchExample(ctx context.Context, in *UpnpSearchRequest, opts ...grpc.CallOption) (Task_UpnpSearchExampleClient, error) {
	stream, err := c.cc.NewStream(ctx, &Task_ServiceDesc.Streams[0], "/task.Task/UpnpSearchExample", opts...)
	if err != nil {
		return nil, err
	}
	x := &taskUpnpSearchExampleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Task_UpnpSearchExampleClient interface {
	Recv() (*UpnpSearchResponse, error)
	grpc.ClientStream
}

type taskUpnpSearchExampleClient struct {
	grpc.ClientStream
}

func (x *taskUpnpSearchExampleClient) Recv() (*UpnpSearchResponse, error) {
	m := new(UpnpSearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskServer is the server API for Task service.
// All implementations must embed UnimplementedTaskServer
// for forward compatibility
type TaskServer interface {
	Foo(context.Context, *FooRequest) (*FooResponse, error)
	UpnpSearchExample(*UpnpSearchRequest, Task_UpnpSearchExampleServer) error
	mustEmbedUnimplementedTaskServer()
}

// UnimplementedTaskServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServer struct {
}

func (UnimplementedTaskServer) Foo(context.Context, *FooRequest) (*FooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Foo not implemented")
}
func (UnimplementedTaskServer) UpnpSearchExample(*UpnpSearchRequest, Task_UpnpSearchExampleServer) error {
	return status.Errorf(codes.Unimplemented, "method UpnpSearchExample not implemented")
}
func (UnimplementedTaskServer) mustEmbedUnimplementedTaskServer() {}

// UnsafeTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServer will
// result in compilation errors.
type UnsafeTaskServer interface {
	mustEmbedUnimplementedTaskServer()
}

func RegisterTaskServer(s grpc.ServiceRegistrar, srv TaskServer) {
	s.RegisterService(&Task_ServiceDesc, srv)
}

func _Task_Foo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).Foo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.Task/Foo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).Foo(ctx, req.(*FooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_UpnpSearchExample_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpnpSearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskServer).UpnpSearchExample(m, &taskUpnpSearchExampleServer{stream})
}

type Task_UpnpSearchExampleServer interface {
	Send(*UpnpSearchResponse) error
	grpc.ServerStream
}

type taskUpnpSearchExampleServer struct {
	grpc.ServerStream
}

func (x *taskUpnpSearchExampleServer) Send(m *UpnpSearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Task_ServiceDesc is the grpc.ServiceDesc for Task service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Task_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Foo",
			Handler:    _Task_Foo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpnpSearchExample",
			Handler:       _Task_UpnpSearchExample_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/task/task.proto",
}
